### ISSUE TITLE
JOSS-review : "Via" - parameters in Rail(UK) by shiny_emissions are not accepted by rail_emissions.R

### ISSUE THREAD

**Issue by hvwaldow** [IDEMSInternational/carbonr#26]
The "Via" - parameters in Rail(UK) by shiny_emissions() are not accepted by rail_emissions.R

if "Via" is set to "1" and "Station" to, e.g., "BPW" then the program fails with

    Error in rail_emissions: Assertion on 'via' failed: Must be of type 'character', not 'list'.

**Comment by lilyclements** [comment]
@hvwaldow this should now be fixed from changes in #32. If you are happy that this now works then let me know and I will close this issue. Thanks!
