### ISSUE TITLE
JOSS-Review License in DESCRIPTION

### ISSUE THREAD

**Issue by hvwaldow** [IDEMSInternational/carbonr#27]
https://github.com/IDEMSInternational/carbonr/blob/53159b99dab599297872b35afc2136e8c2261a02/DESCRIPTION#L8

I wonder why you mention LGPL here in addition to GPL in `LICENSE`. 

1. Alternatives (dual-licensing, the user can choose one) are supposed to be delineated by vertical bars ("|"). See https://cran.rstudio.com/doc/manuals/r-devel/R-exts.html#Licensing.

2. I am not sure what the point of dual-licensing with LGPL and GPL is as this appears to be function equivalent of just using LGPL: https://opensource.stackexchange.com/a/8404 , which would make the whole thing easier. But of course I don't want to push you one way or another. With regard to the review all choices are fine.

**Comment by lilyclements** [comment]
Thanks for this @hvwaldow. This was actually some legacy code - it used to give a bug so was a temporary fix around. Thanks for flagging it and it should be sorted now I hope

**Comment by hvwaldow** [comment]
It seems the line in Description is still the same. I don't get what is meant. Can you tell me in prose under what license(s) you want to make carbon available?

**Comment by lilyclements** [comment]
I would like to make the GNU Lesser General Public License (LGPL) version 3 as the license. Should I put in here "LGPL (>=3)" instead? Thanks, and apologies for my confusion on this!

**Comment by hvwaldow** [comment]
Yes, I think that would be correct.
