### ISSUE TITLE
JOSS-review: Community guidelines

### ISSUE THREAD

**Issue by hvwaldow** [IDEMSInternational/carbonr#28]
This part of the JOSS requirements is not adequately covered:

> There should be clear guidelines for third-parties wishing to:
    + Contribute to the software
    + Report issues or problems with the software
    + Seek support

I think that can be easily fixed by adding one or two sentences in the README.

**Comment by lilyclements** [comment]
@hvwaldow I have added these changes in in PR #30. Are you happy with the changes and for this to be closed?

**Comment by hvwaldow** [comment]
:+1:
