### ISSUE TITLE
JOSS-review: State of the field

### ISSUE THREAD

**Issue by hvwaldow** [IDEMSInternational/carbonr#29]
**In the paper**, could you please mention comparable libraries (R or other languages) that would fulfill a similar function and point out the differences to `carbonr` ? If there aren't any, just mention it ( e.g. "To my knowledge there are no ....")

Also please expand on "Traditional tools for carbon accounting ..." (line 15): One example of such "traditional tool" would be nice.

Also mention some good (as good as it gets) online-calculation tools in the paper (you have 2 in the README).

**Comment by hvwaldow** [comment]
Totally happy with the content. But I believe I found a little grammar-glitch. Please have a look, then close.

**Comment by lilyclements** [comment]
@hvwaldow thanks! This should be fixed now in #34
